accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.school_admin_register, name="school_admin_register"),
    path("login/", views.school_admin_login, name="school_admin_login"),
    path("logout/", views.logout_view, name="logout_view"),
    # forgot password
    path("forgot-password/", views.forgot_password, name="forgot_password"),
    path("otp-confirmation/", views.otp_confirmation, name="otp_confirmation"),
    path(
        "set-new-password/<int:user_id>/",
        views.set_new_password,
        name="set_new_password",
    ),
]

app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("student/", views.student_page, name="student_page"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("app.urls")),
    path("school/", include("school.urls")),
    path("payment/", include("payment.urls")),
    path("api/dashboard/", include("dashboard_api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.urls import path
from school import views

app_name = "school"

urlpatterns = [
    path("register/", views.school_register, name="school_register"),
    path("profile/", views.school_profile, name="school_profile"),
    path("update/", views.school_update, name="school_update"),
    path("grade/", views.grade, name="grade"),
    path("grade/<pk>/delete/", views.grade_delete, name="grade_delete"),
    path("grade/<pk>/update/", views.grade_update, name="grade_update"),
    path("fee/", views.fee, name="fee"),
    path("fee/<pk>/delete/", views.fee_delete, name="fee_delete"),
    path("fee/<pk>/update/", views.fee_update, name="fee_update"),
    path("students/", views.students, name="students"),
    path("students/csv-upload/", views.upload_students_csv, name="upload_students_csv"),
]

school/forms.py
from django import forms
from school.models import School, Grade, Fee
from django.utils.text import slugify
from django.contrib.auth import get_user_model


CustomUser = get_user_model()


class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        exclude = (
            "admin_user",
            "created_at",
            "slug",
            "code",
            "updated_at",
            "is_active",
        )

        widgets = {
            "established_date": forms.DateInput(attrs={"type": "date"}),
            "theme_color": forms.TextInput(attrs={"type": "color"}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request") if "request" in kwargs else None
        super().__init__(*args, **kwargs)

    def save(self, commit=True, *args, **kwargs):
        school = super(SchoolForm, self).save(commit=False, *args, **kwargs)

        if self.request:
            school.admin_user = self.request.user

        if not school.code:
            school_name = self.cleaned_data.get("name")
            school_name_words = school_name.split(" ")
            estd_year = self.cleaned_data.get("established_date").year
            code = "".join([word[0] for word in school_name_words]) + f"-{estd_year}"
            school.code = code
            school.slug = slugify(school_name)

        if commit:
            school.save()

        return school


class GradeForm(forms.ModelForm):
    class Meta:
        model = Grade
        fields = ["name"]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request") if "request" in kwargs else None
        super().__init__(*args, **kwargs)

    def save(self, commit=True, *args, **kwargs):
        grade = super(GradeForm, self).save(commit=False, *args, **kwargs)
        grade.school = self.request.user.school

        if commit:
            grade.save()

        return grade


class FeeForm(forms.ModelForm):
    class Meta:
        model = Fee
        fields = ["name", "amount"]

    def save(self, commit=True, *args, **kwargs):
        grade = kwargs.pop("grade", None)
        fee = super(FeeForm, self).save(commit=False, *args, **kwargs)
        if grade is not None:
            fee.grade = grade

        if commit:
            fee.save()

        return fee


class StudentRegistrationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput,
        required=True,
        help_text="Set an initial password for the student.",
    )
    grade = forms.ModelChoiceField(queryset=Grade.objects.none())

    class Meta:
        model = CustomUser
        fields = [
            "first_name",
            "last_name",
            "grade",
            "email",
            "phone_number",
            "address",
            "password",
        ]

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request") if "request" in kwargs else None
        super().__init__(*args, **kwargs)
        self.fields["grade"].queryset = Grade.objects.filter(
            school=self.request.user.school
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.role = CustomUser.Roles.STUDENT  # enforce role
        user.set_password(self.cleaned_data["password"])  # hash password
        if commit:
            user.save()
        return user


class StudentBulkRegisterForm(forms.Form):
    csv_file = forms.FileField(
        label="CSV File",
        help_text="Upload a CSV file containing student data.",
        required=True,
        widget=forms.FileInput(attrs={"accept": ".csv"}),
    )
    grade = forms.ModelChoiceField(queryset=Grade.objects.none())

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request") if "request" in kwargs else None
        super().__init__(*args, **kwargs)

        self.fields["grade"].queryset = Grade.objects.filter(
            school=self.request.user.school
        )

school/views.py
from urllib.parse import urlencode

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from django.views.decorators.http import require_GET, require_POST

from accounts.models import CustomUser
from school.forms import (
    FeeForm,
    GradeForm,
    SchoolForm,
    StudentBulkRegisterForm,
    StudentRegistrationForm,
)
from school.models import Fee, Grade, TempCSVFile
from school.background_tasks import bulk_create_students_from_csv
from school.filters import StudentFilter
from django.core.paginator import Paginator


@require_POST
def school_register(request):
    form_data = request.POST
    form = SchoolForm(form_data, request.FILES, request=request)
    if form.is_valid():
        form.save()
        return redirect("school:school_profile")

    return render(request, "app/dashboard.html", {"form": form})


@require_GET
@login_required
def school_profile(request):
    school_admin = request.user
    print(school_admin.profile_pic)
    try:
        school_data = school_admin.school
    except Exception as e:
        print(e)
        return redirect("app:dashboard")

    context = {"admin": school_admin, "school": school_data}
    return render(request, "school/profile.html", context)


@login_required
def school_update(request):
    if request.method == "POST":
        form_data = request.POST
        form = SchoolForm(
            form_data, request.FILES, instance=request.user.school, request=request
        )
        if form.is_valid():
            form.save()
            return redirect("school:school_profile")

    form = SchoolForm(instance=request.user.school, request=request)
    form_submission_url = reverse_lazy("school:school_update")

    context = {"form": form, "form_submission_url": form_submission_url}

    return render(request, "school/update-school-info.html", context)


def grade(request):
    if request.method == "POST":
        form = GradeForm(request.POST, request=request)
        if form.is_valid():
            try:
                saved_grade = form.save()
            except IntegrityError:
                return JsonResponse(
                    {"success": False, "message": "Grade already exists."}
                )
            else:
                saved_grade_dict = {"id": saved_grade.id, "name": saved_grade.name}
                return JsonResponse(
                    {
                        "success": True,
                        "message": "Grade added successfully.",
                        "data": saved_grade_dict,
                    }
                )

    form = GradeForm()
    grades_list = request.user.school.classes.all()

    context = {"form": form, "grades_list": grades_list}

    return render(request, "school/grade-create-form.html", context)


def grade_delete(request, pk):
    try:
        Grade.objects.get(id=pk).delete()
    except Grade.DoesNotExist:
        return JsonResponse({"success": False, "message": "Grade doesn't exist."})
    else:
        return JsonResponse({"success": True, "message": "Grade deleted successfully."})


def grade_update(request, pk):
    try:
        grade = Grade.objects.get(pk=pk)
    except Grade.DoesNotExist:
        messages.error(request, "Grade does not exist")
        return redirect("school:grade")

    if request.method == "POST":
        form = GradeForm(request.POST, instance=grade, request=request)
        if form.is_valid():
            form.save()
            messages.success(request, "Grade updated successfully")
            return redirect("school:grade")

        messages.error(request, "Failed to update grade")
        return redirect("school:grade")

    else:
        form = GradeForm(instance=grade, request=request)
        context = {"form": form}
        return render(request, "school/grade-update-form.html", context)


def fee(request):
    if request.method == "POST":
        grade_id = request.POST.get("grade_id")
        try:
            grade = Grade.objects.get(id=grade_id)
        except Grade.DoesNotExist:
            return JsonResponse({"success": False, "message": "Grade does not exist."})

        form = FeeForm(request.POST)
        if form.is_valid():
            try:
                saved_fee = form.save(grade=grade)
            except IntegrityError:
                return JsonResponse(
                    {"success": False, "message": "Fee already exists."}
                )

            reponse = {
                "success": True,
                "message": "Fee added successfully.",
                "data": {
                    "id": saved_fee.id,
                    "name": saved_fee.name,
                    "amount": saved_fee.amount,
                },
            }
            return JsonResponse(reponse)

    grade_id = request.GET.get("grade_id")
    try:
        grade = Grade.objects.get(id=grade_id)
        fees = grade.fees.all()
    except Grade.DoesNotExist:
        messages.error(request, "Grade does not exist")
        return redirect("school:grade")

    form = FeeForm()
    context = {"form": form, "grade": grade, "fees": fees}
    return render(request, "school/fee-create.html", context)


def fee_delete(request, pk):
    try:
        Fee.objects.get(id=pk).delete()
    except Fee.DoesNotExist:
        return JsonResponse({"success": False, "message": "Fee doesn't exist."})
    else:
        return JsonResponse({"success": True, "message": "Fee deleted successfully."})


def fee_update(request, pk):
    try:
        fee = Fee.objects.get(pk=pk)
        base_url = reverse("school:fee")
        query_string = urlencode({"grade_id": fee.grade.id})
        url = f"{base_url}?{query_string}"
    except Fee.DoesNotExist:
        messages.error(request, "fee does not exist")
        return redirect(url)

    if request.method == "POST":
        form = FeeForm(request.POST, instance=fee)
        if form.is_valid():
            form.save()
            messages.success(request, "fee updated successfully")
            return redirect(url)

        messages.error(request, "Failed to update fee")
        return redirect(url)

    else:
        form = FeeForm(instance=fee)
        context = {"form": form}
        return render(request, "school/fee-update.html", context)


def students(request):
    if request.method == "POST":
        form = StudentRegistrationForm(request.POST, request.FILES, request=request)
        if form.is_valid():
            form.save()
            messages.success(request, "Student registered successfully!")
            return redirect("student_register")
    else:
        form = StudentRegistrationForm(request=request)
        csv_form = StudentBulkRegisterForm(request=request)

    all_students = CustomUser.objects.filter(
        role=CustomUser.Roles.STUDENT,
        grade__isnull=False,
        grade__school=request.user.school,
    )
    filtered_students = StudentFilter(request.GET, queryset=all_students)

    paginator = Paginator(
        filtered_students.qs, 10
    )  # Show 10 students records per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "form": form,
        "students": filtered_students.qs,
        "csv_form": csv_form,
        "filter_form": filtered_students.form,
        "page_obj": page_obj,
    }

    return render(request, "school/students.html", context)


def upload_students_csv(request):
    if request.method == "POST":
        form = StudentBulkRegisterForm(request.POST, request.FILES, request=request)
        if form.is_valid():
            saved_file = TempCSVFile.objects.create(file=request.FILES["csv_file"])
            bulk_create_students_from_csv(
                saved_file.id, request.POST.get("grade", None)
            )
            messages.success(request, "Students registered successfully!")
            return redirect("school:students")

    return redirect("school:students")

school/templates/school/fee-create.html
{% extends 'base.html' %}
{% load form_extras %}


{% block title %}
Fee
{% endblock title %}

{% block content %}

<main class=" min-h-screen flex flex-col  gap-5 p-6 w-full" id="main">

    <div class="toast toast-end toast-top">
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-error alert-soft">
            {% else %}
            <div class="alert alert-success alert-soft">
                {% endif %}
                <span>{{message}}</span>
            </div>
            {% endfor %}
        </div>



        <h1 class="text-3xl font-bold mb-4">Add Fee ({{grade.name}})</h1>
        <div class="flex  gap-12">
            <form id="add-fee-form" action="" method="post" class="flex-grow max-w-[500px]">
                {% csrf_token %}
                <input type="hidden" name="grade_id" value="{{grade.id}}">
                <fieldset class="fieldset mb-1">
                    <label class="label text-xl" for="{{ form.name.id_for_label }}">Fee {{form.name.label}}</label>
                    {{ form.name|add_class:"input p-3 mb-1 min-w-[300px] w-full" }}

                    <ul>
                        {% for error in form.name.errors %}
                        <li class="text-red-500 text-sm">{{ error }}</li>
                        {% endfor %}
                    </ul>

                </fieldset>
                <fieldset class="fieldset mb-1">
                    <label class="label text-xl" for="{{ form.amount.id_for_label }}">{{form.amount.label}}</label>
                    {{ form.amount|add_class:"input p-3 mb-1 min-w-[300px] w-full" }}

                    <ul>
                        {% for error in form.amount.errors %}
                        <li class="text-red-500 text-sm">{{ error }}</li>
                        {% endfor %}
                    </ul>

                </fieldset>
                <button type="submit" class="btn btn-primary">Add Fee</button>
            </form>
            <div class="flex-grow">
                <h1 class="text-2xl font-bold mb-4">Fees List ({{grade.name}}) </h1>
                <div class="overflow-x-auto rounded-box border border-base-content/5 bg-base-100">
                    <table class="table">
                        <!-- head -->
                        <thead>
                            <tr>
                                <th>SN</th>
                                <th>Fee Name</th>
                                <th>Amount</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="fee-list">

                            {% for fee in fees %}
                            <tr id="fee-{{fee.id}}">
                                <th>{{ forloop.counter }}</th>
                                <td>{{ fee.name }}</td>
                                <td>{{ fee.amount }}</td>
                                <td>
                                    <div class="flex gap-2">
                                        <a href="{% url 'school:fee_update' fee.id %}"
                                            class="btn btn-sm btn-primary">Update</a>

                                        <button data-fee-id="{{fee.id}}" class="btn btn-sm btn-error"
                                            onclick="delete_fee(this)">Delete</button>
                                    </div>

                                </td>
                            </tr>

                            {% endfor %}

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
</main>

<script>

    function remove_fee_from_table(fee_id) {
        const row_id_to_be_deleted = `fee-${fee_id}`
        const row_to_be_deleted = document.getElementById(row_id_to_be_deleted)
        row_to_be_deleted.remove()

    }

    function delete_fee(btnElement) {
        const fee_id = btnElement.dataset.feeId

        fetch("{% url 'school:fee_delete' 'dummy' %}".replace('dummy', fee_id))
            .then((response) => response.json())
            .then((data) => {
                if (data.success) {
                    show_toast_message(data.message, success = true)
                    remove_fee_from_table(fee_id)
                } else {
                    show_toast_message(`Error: ${data.message}`, success = false)
                }
            })
            .catch((err) => console.error(err));

    }

    function show_toast_message(message, success = true) {
        const mainDiv = document.getElementById("main")
        const toastDiv = document.getElementById("toast-message")

        toastDiv?.remove()

        mainDiv.insertAdjacentHTML("afterbegin", `    
            <div class="toast toast-end toast-top" id="toast-message">
                <div class="alert alert-${success === true ? "success" : "error"} alert-soft">
                    <span>${message}</span>
                </div>
            </div>
        `)
    }

    function add_fee_to_table(fee) {
        const table_body = document.getElementById("fee-list");
        const rows_count = table_body.children.length
        const table_row = document.createElement("tr")
        table_row.id = `fee-${fee.id}`
        const dummy_url = "{% url 'school:fee_update' 'dummy' %}";


        table_row.innerHTML = `
                            <th>${rows_count + 1}</th>
                            <td>${fee.name}</td>
                            <td>${fee.name}</td>
                            <td>
                                <div class="flex gap-2">
                                     <a href="${dummy_url.replace('dummy', fee.id)}"
                                            class="btn btn-sm btn-primary">Update</a>

                                        <button data-fee-id="${fee.id}" class="btn btn-sm btn-error"
                                            onclick="delete_fee(this)">Delete</button>

                                </div>    
                            </td>
            `

        table_body.appendChild(table_row)

    }


    document
        .getElementById("add-fee-form")
        .addEventListener("submit", function (e) {
            e.preventDefault(); // Prevent the form from submitting normally, which would cause a page reload

            const formData = new FormData(this); // this means, current target html element,which is in this case is our add-fee-form

            const csrf_token = document.getElementsByName("csrfmiddlewaretoken")[0].value;


            fetch("{% url 'school:fee' %}", {
                method: "POST",
                headers: { "X-CSRFToken": csrf_token },
                body: formData,
            })
                .then((response) => response.json())
                .then((data) => {
                    if (data.success) {
                        show_toast_message(data.message, success = true)
                        add_fee_to_table(data.data)
                    } else {
                        show_toast_message(`Error: ${data.message}`, success = false)
                    }
                })
                .catch((err) => console.error(err));
        });

</script>

{% endblock content %}

school/templates/school/fee-update.html
{% extends 'base.html' %}
{% load form_extras %}


{% block title %}
Fee Update
{% endblock title %}

{% block content %}

<main class=" min-h-screen flex flex-col  gap-5 p-6 w-full" id="main">

    <div class="toast toast-end toast-top">
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-error alert-soft">
            {% else %}
            <div class="alert alert-success alert-soft">
                {% endif %}
                <span>{{message}}</span>
            </div>
            {% endfor %}
        </div>



        <h1 class="text-3xl font-bold mb-4">Update Fee</h1>
        <div class="flex  gap-12">
            <form id="add-fee-form" action="" method="post" class="flex-grow max-w-[500px]">
                {% csrf_token %}
                <input type="hidden" name="grade_id" value="{{grade.id}}">
                <fieldset class="fieldset mb-1">
                    <label class="label text-xl" for="{{ form.name.id_for_label }}">Fee {{form.name.label}}</label>
                    {{ form.name|add_class:"input p-3 mb-1 min-w-[300px] w-full" }}

                    <ul>
                        {% for error in form.name.errors %}
                        <li class="text-red-500 text-sm">{{ error }}</li>
                        {% endfor %}
                    </ul>

                </fieldset>
                <fieldset class="fieldset mb-1">
                    <label class="label text-xl" for="{{ form.amount.id_for_label }}">{{form.amount.label}}</label>
                    {{ form.amount|add_class:"input p-3 mb-1 min-w-[300px] w-full" }}

                    <ul>
                        {% for error in form.amount.errors %}
                        <li class="text-red-500 text-sm">{{ error }}</li>
                        {% endfor %}
                    </ul>

                </fieldset>
                <button type="submit" class="btn btn-primary">Update Fee</button>
            </form>

        </div>
</main>

{% endblock content %}

school/templates/school/grade-create-form.html
{% extends 'base.html' %}
{% load form_extras %}


{% block title %}
Class
{% endblock title %}

{% block content %}

<main class=" min-h-screen flex flex-col  gap-5 p-6 w-full" id="main">

    <div class="toast toast-end toast-top">
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="alert alert-error alert-soft">
            {% else %}
            <div class="alert alert-success alert-soft">
                {% endif %}
                <span>{{message}}</span>
            </div>
            {% endfor %}
        </div>



        <h1 class="text-3xl font-bold mb-4">Add Grades</h1>
        <div class="flex  gap-12">
            <form id="add-class-form" action="" method="post" class="flex-grow max-w-[500px]">
                {% csrf_token %}
                <fieldset class="fieldset mb-1">
                    <label class="label text-xl" for="{{ form.name.id_for_label }}">{{form.name.label}}</label>
                    {{ form.name|add_class:"input p-3 mb-1 min-w-[300px] w-full" }}

                    <ul>
                        {% for error in form.name.errors %}
                        <li class="text-red-500 text-sm">{{ error }}</li>
                        {% endfor %}
                    </ul>

                </fieldset>
                <button type="submit" class="btn btn-primary">Add Class</button>
            </form>
            <div class="flex-grow">
                <h1 class="text-2xl font-bold mb-4">Grades List</h1>
                <div class="overflow-x-auto rounded-box border border-base-content/5 bg-base-100">
                    <table class="table">
                        <!-- head -->
                        <thead>
                            <tr>
                                <th>SN</th>
                                <th>Grade Name</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="grade-list">

                            {% for grade in grades_list %}
                            <!-- row -->
                            <tr id="grade-{{grade.id}}">
                                <th>{{ forloop.counter }}</th>
                                <td>{{ grade.name }}</td>
                                <td>
                                    <div class="flex gap-2">
                                        <a href="{% url 'school:grade_update' grade.id %}"
                                            class="btn btn-sm btn-primary">Update</a>
                                        <button data-grade-id="{{grade.id}}" class="btn btn-sm btn-error"
                                            onclick="delete_grade(this)">Delete</button>

                                    </div>

                                </td>
                            </tr>

                            {% endfor %}

                        </tbody>
                    </table>
                </div>

            </div>
        </div>
</main>

<script>

    function remove_grade_from_table(grade_id) {
        const row_id_to_be_deleted = `grade-${grade_id}`
        const row_to_be_deleted = document.getElementById(row_id_to_be_deleted)
        row_to_be_deleted.remove()

    }

    function delete_grade(btnElement) {
        const grade_id = btnElement.dataset.gradeId

        fetch("{% url 'school:grade_delete' 'dummy' %}".replace('dummy', grade_id))
            .then((response) => response.json())
            .then((data) => {
                if (data.success) {
                    show_toast_message(data.message, success = true)
                    remove_grade_from_table(grade_id)
                } else {
                    show_toast_message(`Error: ${data.message}`, success = false)
                }
            })
            .catch((err) => console.error(err));

    }

    function show_toast_message(message, success = true) {
        const mainDiv = document.getElementById("main")
        const toastDiv = document.getElementById("toast-message")

        toastDiv?.remove()

        mainDiv.insertAdjacentHTML("afterbegin", `    
            <div class="toast toast-end toast-top" id="toast-message">
                <div class="alert alert-${success === true ? "success" : "error"} alert-soft">
                    <span>${message}</span>
                </div>
            </div>
        `)
    }

    function add_grade_to_table(grade) {
        const table_body = document.getElementById("grade-list");
        const rows_count = table_body.children.length
        const table_row = document.createElement("tr")
        table_row.id = `grade-${grade.id}`

        table_row.innerHTML = `
                            <th>${rows_count + 1}</th>
                            <td>${grade.name}</td>
                            <td>
                                <div class="flex gap-2">
                                    <button class="btn btn-sm btn-primary">Update</button>
                                    <button data-grade-id="${grade.id}" class="btn btn-sm btn-error"
                                        onclick="delete_grade(this)">Delete</button>

                                </div>    
                            </td>
            `

        table_body.appendChild(table_row)

    }


    document
        .getElementById("add-class-form")
        .addEventListener("submit", function (e) {
            e.preventDefault(); // Prevent the form from submitting normally, which would cause a page reload

            const formData = new FormData(this); // this means, current target html element,which is in this case is our add-class-form

            const csrf_token = document.getElementsByName("csrfmiddlewaretoken")[0].value;



            fetch("{% url 'school:grade' %}", {
                method: "POST",
                headers: { "X-CSRFToken": csrf_token },
                body: formData,
            })
                .then((response) => response.json())
                .then((data) => {
                    if (data.success) {
                        show_toast_message(data.message, success = true)
                        add_grade_to_table(data.data)
                    } else {
                        show_toast_message(`Error: ${data.message}`, success = false)
                    }
                })
                .catch((err) => console.error(err));
        });

</script>

{% endblock content %}

school/templates/school/grade-update-form.html
{% extends 'base.html' %}
{% load form_extras %}


{% block title %}
Class Update
{% endblock title %}

{% block content %}

<main class=" min-h-screen flex flex-col  gap-5 p-6 w-full" id="main">
    <h1 class="text-3xl font-bold mb-4">Update Grade</h1>
    <div class="flex  gap-12">
        <form action="" method="post" class="flex-grow max-w-[500px]">
            {% csrf_token %}
            <fieldset class="fieldset mb-1">
                <label class="label text-xl" for="{{ form.name.id_for_label }}">{{form.name.label}}</label>
                {{ form.name|add_class:"input p-3 mb-1 min-w-[300px] w-full" }}

                <ul>
                    {% for error in form.name.errors %}
                    <li class="text-red-500 text-sm">{{ error }}</li>
                    {% endfor %}
                </ul>

            </fieldset>
            <button type="submit" class="btn btn-primary">Update Class</button>
        </form>

    </div>
</main>

{% endblock content %}

school/templates/school/update-school-info.html
{% extends 'base.html' %}

{% block title %}Update School Info{% endblock title %}


{% block content %}

{% include 'school/registration-form.html' with form=form %}

{% endblock content %}