app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("student/", views.student_page, name="student_page"),
]

payment/urls.py
from django.urls import path
from payment import views

app_name = "payment"

urlpatterns = [
    path("transactions/", views.transactions, name="transactions"),
    path("due-payments/", views.due_payments, name="due_payments"),
    path("payment/", views.payment, name="payment"),
    path("payment/done/", views.payment_done, name="payment_done"),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("app.urls")),
    path("school/", include("school.urls")),
    path("payment/", include("payment.urls")),
    path("api/dashboard/", include("dashboard_api.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models
import uuid


class Payment(models.Model):
    class Status(models.TextChoices):
        INITIATED = "INITIATED", "Initiated"
        SUCCESS = "SUCCESS", "Success"
        FAILED = "FAILED", "Failed"
        PENDING = "PENDING", "Pending"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    student = models.ForeignKey(
        "accounts.CustomUser", on_delete=models.CASCADE, related_name="payments"
    )
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    name = models.CharField(max_length=150, blank=True)  # will set in save()

    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.INITIATED
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # khalti infos
    initial_khalti_id = models.CharField(
        max_length=255, null=True, blank=True, editable=False
    )
    khalti_status = models.CharField(
        max_length=50, null=True, blank=True, editable=False
    )
    khalti_transaction_id = models.CharField(
        max_length=255, null=True, blank=True, editable=False
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.name:  # only set name if it's not already provided
            # Count how many payments this student has already made in this grade
            previous_count = Payment.objects.filter(
                student=self.student, status=Payment.Status.SUCCESS
            ).count()
            self.name = f"Installment {previous_count + 1}"
        super().save(*args, **kwargs)

payment/views.py
from django.shortcuts import render, redirect
from school.models import Fee, Grade
from django.db import models
from django.views.decorators.http import require_POST
import requests
import json
from django.urls import reverse
from payment.models import Payment
from django.contrib import messages
from django.conf import settings


def transactions(request):
    transactions = request.user.payments.all().order_by("-updated_at")

    context = {"transactions": transactions}

    return render(request, "payment/transactions.html", context)


def due_payments(request):
    grade_fee = Grade.get_total_fees(request.user.grade)
    previous_payment_total = request.user.payments.filter(
        status=Payment.Status.SUCCESS
    ).aggregate(grand_total=models.Sum("amount"))
    if previous_payment_total["grand_total"] is None:
        due_fee = grade_fee["grand_total"]
    else:
        due_fee = grade_fee["grand_total"] - previous_payment_total["grand_total"]

    context = {
        "grade_fee": grade_fee["grand_total"],
        "fee_structure": grade_fee["fee_structure_description"],
        "due_fee": due_fee,
    }

    return render(request, "payment/due-payments.html", context)


@require_POST
def payment(request):
    # print("payment", request.POST)
    url = f"{settings.KHALTI_BASE_URL}{settings.KHALTI_INITIATE_URL}"

    try:
        new_payment = Payment.objects.create(
            student=request.user, amount=request.POST.get("amount")
        )
    except Exception as e:
        print(e)
        return redirect("payment:due_payments")

    print(new_payment.id, new_payment.name, new_payment.amount, new_payment.student)

    payload = json.dumps(
        {
            "return_url": request.build_absolute_uri(reverse("payment:payment_done")),
            "website_url": request.build_absolute_uri("/"),
            "amount": f"{int(float(new_payment.amount) * 100)}",  # in paisa
            "purchase_order_id": f"{new_payment.id}",
            "purchase_order_name": f"{new_payment.name}",
            "customer_info": {
                "name": f"{request.user.first_name} {request.user.last_name}",
                "email": f"{request.user.email}",
                "phone": f"{request.user.phone_number}",
            },
        }
    )
    headers = {
        "Authorization": f"key {settings.KHALTI_SECRET}",
        "Content-Type": "application/json",
    }

    response = requests.request("POST", url, headers=headers, data=payload)

    print(response.text)
    return redirect(response.json()["payment_url"])


def payment_done(request):
    # print("payment done")
    query_params = request.GET
    payment_id = query_params.get("purchase_order_id")
    initial_payment_id = query_params.get("pidx")
    status = query_params.get("status")  # if not "Completed" then failed
    amount_in_paisa = int(query_params.get("amount"))
    total_amount_in_paisa = query_params.get("total_amount")
    payment_name = query_params.get("purchase_order_name")
    phone_number = query_params.get("mobile")
    khalti_transaction_id = query_params.get("transaction_id")

    # print("-----------request.GET-------------")
    # print(request.GET)
    # print("-----------request.GET-------------")

    verification_url = f"{settings.KHALTI_BASE_URL}{settings.KHALTI_LOOKUP_URL}"

    payload = json.dumps({"pidx": initial_payment_id})
    headers = {
        "Authorization": f"key {settings.KHALTI_SECRET}",
        "Content-Type": "application/json",
    }

    response = requests.request("POST", verification_url, headers=headers, data=payload)

    result = response.json()
    # print("-----------result-------------")
    # print(result)
    # print("-----------result-------------")
    try:
        payment = Payment.objects.get(id=payment_id)  # get the payment object
    except Exception as e:  # if anything wrong happens while getting the payment object
        print(e)
        messages.error(request, "Payment details not found")
        return redirect("payment:due_payments")

    if (  # verification of payment response from khalti with lookup/verification api of khalti
        result["status"] == status
        and result["total_amount"] == amount_in_paisa
        and result["transaction_id"] == khalti_transaction_id
    ):
        if (
            (payment.amount * 100) == result["total_amount"]
        ):  # if amount is not modified by middleman, amount *100, is equal to total_amount
            if result["status"] == "Completed":
                payment.status = Payment.Status.SUCCESS
            elif result["status"] in ("Expired", "Failed", "User canceled"):
                payment.status = Payment.Status.FAILED
            else:
                payment.status = Payment.Status.PENDING

            payment.khalti_status = result["status"]
            payment.khalti_transaction_id = result["transaction_id"]
            payment.initial_khalti_id = result["pidx"]
            payment.save()  # save the payment object with latest khalti details
        else:
            messages.error(request, "Payment amount verification failed")
            return redirect(
                "payment:due_payments"
            )  # redirect to due payments page if payment amount is modified by middleman
    else:
        messages.error(request, "Payment details verification failed")
        payment.status = Payment.Status.FAILED
        payment.save()
        return redirect("payment:due_payments")

    return redirect("payment:transactions")

payment/templates/payment/due-payments.html
{% extends "base.html" %}

{% block title %}
Fee Due
{% endblock title %}

{% block sidebar %}
{% endblock sidebar %}

{% block content %}
<main class="min-h-screen w-full flex flex-col items-center p-8 bg-base-100">
    <div class="toast toast-end toast-top">
        {% for message in messages %}
        <div class="alert alert-error alert-soft">
            <span>{{message}}</span>
        </div>
        {% endfor %}
    </div>

    <div class="w-full flex flex-col items-center max-w-3xl shadow-lg rounded-2xl p-8">
        <h1 class="text-3xl font-bold mb-6 text-center">
            💰 Fee Due: Rs. {{ due_fee }}
        </h1>


        <p class="text-md font-semibold mb-6 ">Total Fee: Rs. {{ grade_fee }}</p>


        <form action="{% url 'payment:payment' %}" method="post" class="flex gap-2 items-baseline">
            {% csrf_token %}
            <fieldset class="fieldset mb-4">
                <legend class="fieldset-legend text-xl">Amount in Rs.</legend>
                <input type="number" name="amount" id="amount" value="{{ due_fee }}" class="input input-bordered w-full"
                    required>
            </fieldset>
            <button type="submit" class="btn btn-primary">Make Payment</button>
        </form>
        <div
            class="bg-base-100 rounded-xl p-6 font-mono text-md line-height-relaxed whitespace-pre-line leading-relaxed">
            {{ fee_structure|linebreaksbr }}
        </div>
    </div>
</main>
{% endblock %}

payment/templates/payment/transactions.html
{% extends "base.html" %}

{% block title %}
Fee Due
{% endblock title %}

{% block sidebar %}
{% endblock sidebar %}

{% block content %}
<main class="min-h-screen w-full flex flex-col items-center p-8 bg-base-100">
    <div class="flex gap-6">

        <h1 class="text-3xl font-bold  mb-6 text-center">
            💰 Transactions
        </h1>
        <a href="{% url 'app:student_page' %}" class="btn btn-sm btn-primary">Home</a>
    </div>
    <div class="overflow-x-auto rounded-box border border-base-content/5 bg-base-100">
        <table class="table w-full">
            <!-- head -->
            <thead>
                <tr>
                    <th>SN</th>
                    <th>Name</th>
                    <th>Amount (Rs.)</th>

                    <th>Student</th>
                    <th>Status</th>

                    <th>Payment Completed At</th>
                </tr>
            </thead>
            <tbody>
                {% for transaction in transactions %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>{{ transaction.name }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.student.get_full_name }}</td>
                    <td class="{% if transaction.status != 'SUCCESS' %} line-through {% endif %} ">
                        {{ transaction.status}}</td>
                    <td>{{ transaction.updated_at }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

</main>
{% endblock %}